# Pre-commit 配置文件
repos:
  # Ruff - 快速 Python 代码检查
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  # Black - 代码格式化
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.13

  # Mypy - 类型检查
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--config-file=mypy.ini]

  # Bandit - 安全扫描
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: [-r, app/]
        exclude: ^(migrations/|userdata/|tests/|venv/|\.venv/|__pycache__/|\.git/|node_modules/)

  # 通用检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: fix-byte-order-marker

  # 自定义脚本
  - repo: local
    hooks:
      - id: quality-check
        name: 代码质量检查
        entry: uv run python scripts/quality_check.py
        language: system
        files: \.py$
        pass_filenames: false
