# 本地开发环境配置（macOS，无代理）
# 包含：PostgreSQL、Redis、Nginx、Flask应用
# 使用命名卷进行数据持久化

volumes:
  whalefall_postgres_data:
    driver: local
  whalefall_redis_data:
    driver: local
  whalefall_nginx_logs:
    driver: local
  whalefall_nginx_ssl:
    driver: local
  # whalefall_app_data:  # 移除Flask应用持久化卷
  #   driver: local

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: whalefall_postgres_dev
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-whalefall_dev}
      - POSTGRES_USER=${POSTGRES_USER:-whalefall_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    ports:
      - "5432:5432"
    volumes:
      - whalefall_postgres_data:/var/lib/postgresql/data
    networks:
      - whalefall_dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-whalefall_user} -d ${POSTGRES_DB:-whalefall_dev}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: whalefall_redis_dev
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - whalefall_redis_data:/data
    networks:
      - whalefall_dev_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: whalefall_nginx_dev
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - whalefall_nginx_logs:/var/log/nginx
      - whalefall_nginx_ssl:/etc/nginx/ssl
    networks:
      - whalefall_dev_network
    # 基础环境中不依赖whalefall服务
    # depends_on:
    #   - whalefall
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

  # Flask应用（开发环境）
  whalefall:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
      args:
        BUILDKIT_INLINE_CACHE: 1
    image: whalefall:dev
    container_name: whalefall_app_dev
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
      - FLASK_HOST=${FLASK_HOST:-0.0.0.0}
      - FLASK_PORT=${FLASK_PORT:-5001}
      - DATABASE_URL=${DATABASE_URL_DOCKER}
      - CACHE_TYPE=${CACHE_TYPE}
      - CACHE_REDIS_URL=${CACHE_REDIS_URL}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - BCRYPT_LOG_ROUNDS=${BCRYPT_LOG_ROUNDS}
      - LOG_LEVEL=${LOG_LEVEL}
      - APP_NAME=${APP_NAME}
      - APP_VERSION=${APP_VERSION}
      - PERMANENT_SESSION_LIFETIME=${PERMANENT_SESSION_LIFETIME}
    # 移除持久化卷，使用容器内临时存储
    # volumes:
    #   - whalefall_app_data:/app/userdata
    #   - ./app:/app/app:ro
    #   - ./migrations:/app/migrations:ro
    #   - ./sql:/app/sql:ro
    ports:
      - "5001:5001"
    networks:
      - whalefall_dev_network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    profiles:
      - flask

networks:
  whalefall_dev_network:
    driver: bridge
