version: '3.9'

services:
  # 本地Nginx反向代理 - 代理到本地Flask应用
  nginx:
    image: nginx:alpine
    container_name: whalefall_nginx_local
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/local/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/local/ssl:/etc/nginx/ssl:ro
      - ./userdata/nginx/logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'
