version: '3.9'

# 基础环境部署配置
# 包含：PostgreSQL、Redis、Nginx
# 不包含：Flask应用（单独部署）

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: whalefall_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-whalefall_prod}
      - POSTGRES_USER=${POSTGRES_USER:-whalefall_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./userdata/postgres:/var/lib/postgresql/data
      - ./sql/init_postgresql.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./sql/permission_configs.sql:/docker-entrypoint-initdb.d/permission_configs.sql:ro
      - ./sql/init_scheduler_tasks.sql:/docker-entrypoint-initdb.d/init_scheduler_tasks.sql:ro
    ports:
      - "5432:5432"
    networks:
      - whalefall_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-whalefall_user} -d ${POSTGRES_DB:-whalefall_prod}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: whalefall_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - ./userdata/redis:/data
    ports:
      - "6379:6379"
    networks:
      - whalefall_network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: whalefall_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./userdata/nginx/logs:/var/log/nginx
      - ./userdata/nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - whalefall_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

networks:
  whalefall_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
