version: '3.8'

services:
  # Oracle数据库
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: taifish-oracle
    environment:
      - ORACLE_PWD=Oracle123
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"  # Oracle Enterprise Manager
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - taifish-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/Oracle123@//localhost:1521/XE", "@/opt/oracle/healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # SQL Server数据库
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taifish-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SqlServer123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - taifish-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P SqlServer123! -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  oracle_data:
    driver: local
  sqlserver_data:
    driver: local

networks:
  taifish-network:
    driver: bridge
