version: '3.9'

# Flask生产环境部署配置
# 包含：Flask应用、APScheduler
# 依赖：基础环境（PostgreSQL、Redis、Nginx）

services:
  # Flask应用
  whalefall:
    image: whalefall:latest
    container_name: whalefall_app
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-whalefall_user}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-whalefall_prod}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - BCRYPT_LOG_ROUNDS=${BCRYPT_LOG_ROUNDS:-12}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - APP_NAME=${APP_NAME:-鲸落}
      - APP_VERSION=${APP_VERSION:-4.0.0}
      - PERMANENT_SESSION_LIFETIME=${PERMANENT_SESSION_LIFETIME:-3600}
    env_file:
      - .env
    volumes:
      - /opt/whale_fall_data/app:/app/userdata
      - /opt/whale_fall_data/logs:/app/userdata/logs
    # 注意：Flask应用依赖基础环境，请确保基础环境已启动
    # 基础环境包含：postgres、redis、nginx
    networks:
      - whalefall_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'

networks:
  whalefall_network:
    external: true
