# Ruff 配置文件 - 基本版本
target-version = "py313"
line-length = 120

exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    ".pytest_cache",
    "migrations",
    "userdata",
    "node_modules",
    "*.pyc",
    ".DS_Store"
]

# 启用核心规则
[lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "ARG",  # flake8-unused-arguments
    "SIM",  # flake8-simplify
    "TCH",  # flake8-type-checking
    "PIE",  # flake8-pie
    "A",    # flake8-builtins
    "COM",  # flake8-commas
    "C90",  # mccabe
    "DJ",   # flake8-django
    "EM",   # flake8-errmsg
    "EXE",  # flake8-executable
    "FA",   # flake8-future-annotations
    "ISC",  # flake8-implicit-str-concat
    "ICN",  # flake8-import-conventions
    "G",    # flake8-logging-format
    "INP",  # flake8-no-pep420
    "T20",  # flake8-print
    "PYI",  # flake8-pyi
    "PT",   # flake8-pytest-style
    "Q",    # flake8-quotes
    "RSE",  # flake8-raise
    "RET",  # flake8-return
    "SLF",  # flake8-self
    "SLOT", # flake8-slots
    "TID",  # flake8-tidy-imports
    "YTT",  # flake8-2020
    "ANN",  # flake8-annotations
    "S",    # flake8-bandit
    "FBT",  # flake8-boolean-trap
    "DTZ",  # flake8-datetimez
    "T10",  # flake8-debugger
]

# 忽略与 Black 冲突的规则
ignore = [
    "E501",  # 行太长 - 由 Black 处理
    "E203",  # 冒号前空格 - 与 Black 冲突
    "COM812",  # 缺少尾随逗号 - 由 Black 处理
    "ISC001",  # 隐式字符串连接 - 有时需要
    "Q000",  # 单引号 - 由 Black 处理
    "Q001",  # 双引号 - 由 Black 处理
    "Q002",  # 三引号 - 由 Black 处理
    "Q003",  # 转义序列 - 由 Black 处理
]

# 复杂度限制
[lint.mccabe]
max-complexity = 10

# 导入排序配置
[lint.isort]
known-first-party = ["app"]
