#!/usr/bin/env python3

"""
泰摸鱼吧 - 权限配置初始化脚本
基于当前数据库实际状态生成完整的权限配置
"""

import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from datetime import datetime

from app import create_app, db
from app.models.permission_config import PermissionConfig


def init_permission_config():
    """初始化权限配置"""
    app = create_app()

    with app.app_context():
        print("开始初始化权限配置...")

        # 清空现有权限配置
        PermissionConfig.query.delete()
        db.session.commit()
        print("已清空现有权限配置")

        # MySQL权限配置
        mysql_permissions = [
            # 全局权限（服务器权限）
            ('mysql', 'global_privileges', 'ALTER', '修改表结构', 1),
            ('mysql', 'global_privileges', 'ALTER ROUTINE', '修改存储过程和函数', 2),
            ('mysql', 'global_privileges', 'CREATE', '创建数据库和表', 3),
            ('mysql', 'global_privileges', 'CREATE ROUTINE', '创建存储过程和函数', 4),
            ('mysql', 'global_privileges', 'CREATE TEMPORARY TABLES', '创建临时表', 5),
            ('mysql', 'global_privileges', 'CREATE USER', '创建用户权限', 6),
            ('mysql', 'global_privileges', 'CREATE VIEW', '创建视图', 7),
            ('mysql', 'global_privileges', 'DELETE', '删除数据', 8),
            ('mysql', 'global_privileges', 'DROP', '删除数据库和表', 9),
            ('mysql', 'global_privileges', 'EVENT', '创建、修改、删除事件', 10),
            ('mysql', 'global_privileges', 'EXECUTE', '执行存储过程和函数', 11),
            ('mysql', 'global_privileges', 'FILE', '文件操作权限', 12),
            ('mysql', 'global_privileges', 'GRANT OPTION', '授权权限，可以授予其他用户权限', 13),
            ('mysql', 'global_privileges', 'INDEX', '创建和删除索引', 14),
            ('mysql', 'global_privileges', 'INSERT', '插入数据', 15),
            ('mysql', 'global_privileges', 'LOCK TABLES', '锁定表', 16),
            ('mysql', 'global_privileges', 'PROCESS', '查看所有进程', 17),
            ('mysql', 'global_privileges', 'REFERENCES', '引用权限', 18),
            ('mysql', 'global_privileges', 'RELOAD', '重载权限表', 19),
            ('mysql', 'global_privileges', 'REPLICATION CLIENT', '复制客户端权限', 20),
            ('mysql', 'global_privileges', 'REPLICATION SLAVE', '复制从库权限', 21),
            ('mysql', 'global_privileges', 'SELECT', '查询数据', 22),
            ('mysql', 'global_privileges', 'SHOW DATABASES', '显示所有数据库', 23),
            ('mysql', 'global_privileges', 'SHOW VIEW', '显示视图', 24),
            ('mysql', 'global_privileges', 'SHUTDOWN', '关闭MySQL服务器', 25),
            ('mysql', 'global_privileges', 'SUPER', '超级权限，可以执行任何操作', 26),
            ('mysql', 'global_privileges', 'TRIGGER', '创建和删除触发器', 27),
            ('mysql', 'global_privileges', 'UPDATE', '更新数据', 28),
            ('mysql', 'global_privileges', 'USAGE', '无权限，仅用于连接', 29),

            # 数据库权限
            ('mysql', 'database_privileges', 'CREATE', '创建数据库和表', 1),
            ('mysql', 'database_privileges', 'DROP', '删除数据库和表', 2),
            ('mysql', 'database_privileges', 'ALTER', '修改数据库和表结构', 3),
            ('mysql', 'database_privileges', 'INDEX', '创建和删除索引', 4),
            ('mysql', 'database_privileges', 'INSERT', '插入数据', 5),
            ('mysql', 'database_privileges', 'UPDATE', '更新数据', 6),
            ('mysql', 'database_privileges', 'DELETE', '删除数据', 7),
            ('mysql', 'database_privileges', 'SELECT', '查询数据', 8),
            ('mysql', 'database_privileges', 'CREATE TEMPORARY TABLES', '创建临时表', 9),
            ('mysql', 'database_privileges', 'LOCK TABLES', '锁定表', 10),
            ('mysql', 'database_privileges', 'EXECUTE', '执行存储过程和函数', 11),
            ('mysql', 'database_privileges', 'CREATE VIEW', '创建视图', 12),
            ('mysql', 'database_privileges', 'SHOW VIEW', '显示视图', 13),
            ('mysql', 'database_privileges', 'CREATE ROUTINE', '创建存储过程和函数', 14),
            ('mysql', 'database_privileges', 'ALTER ROUTINE', '修改存储过程和函数', 15),
            ('mysql', 'database_privileges', 'EVENT', '创建、修改、删除事件', 16),
            ('mysql', 'database_privileges', 'TRIGGER', '创建和删除触发器', 17),
        ]

        # PostgreSQL权限配置
        postgresql_permissions = [
            # 预定义角色
            ('postgresql', 'predefined_roles', 'SUPERUSER', '超级用户角色，拥有所有权限', 1),
            ('postgresql', 'predefined_roles', 'CREATEDB', '创建数据库角色', 2),
            ('postgresql', 'predefined_roles', 'CREATEROLE', '创建角色角色', 3),
            ('postgresql', 'predefined_roles', 'INHERIT', '继承权限角色', 4),
            ('postgresql', 'predefined_roles', 'LOGIN', '登录角色', 5),
            ('postgresql', 'predefined_roles', 'REPLICATION', '复制角色', 6),
            ('postgresql', 'predefined_roles', 'BYPASSRLS', '绕过行级安全角色', 7),
            ('postgresql', 'predefined_roles', 'CONNECTION LIMIT', '连接限制角色', 8),
            ('postgresql', 'predefined_roles', 'VALID UNTIL', '有效期限制角色', 9),
            ('postgresql', 'predefined_roles', 'PASSWORD', '密码角色', 10),

            # 角色属性
            ('postgresql', 'role_attributes', 'SUPERUSER', '超级用户属性', 1),
            ('postgresql', 'role_attributes', 'CREATEDB', '创建数据库属性', 2),
            ('postgresql', 'role_attributes', 'CREATEROLE', '创建角色属性', 3),
            ('postgresql', 'role_attributes', 'INHERIT', '继承权限属性', 4),
            ('postgresql', 'role_attributes', 'LOGIN', '登录属性', 5),
            ('postgresql', 'role_attributes', 'REPLICATION', '复制属性', 6),
            ('postgresql', 'role_attributes', 'BYPASSRLS', '绕过行级安全属性', 7),
            ('postgresql', 'role_attributes', 'CONNECTION LIMIT', '连接限制属性', 8),
            ('postgresql', 'role_attributes', 'VALID UNTIL', '有效期限制属性', 9),
            ('postgresql', 'role_attributes', 'PASSWORD', '密码属性', 10),

            # 数据库权限
            ('postgresql', 'database_privileges', 'CONNECT', '连接数据库权限', 1),
            ('postgresql', 'database_privileges', 'CREATE', '创建对象权限', 2),
            ('postgresql', 'database_privileges', 'TEMPORARY', '创建临时表权限', 3),
            ('postgresql', 'database_privileges', 'TEMP', '创建临时表权限（别名）', 4),

            # 表空间权限
            ('postgresql', 'tablespace_privileges', 'CREATE', '在表空间中创建对象权限', 1),
            ('postgresql', 'tablespace_privileges', 'USAGE', '使用表空间权限', 2),
        ]

        # SQL Server权限配置
        sqlserver_permissions = [
            # 服务器角色
            ('sqlserver', 'server_roles', 'sysadmin', '系统管理员', 1),
            ('sqlserver', 'server_roles', 'serveradmin', '服务器管理员', 2),
            ('sqlserver', 'server_roles', 'securityadmin', '安全管理员', 3),
            ('sqlserver', 'server_roles', 'processadmin', '进程管理员', 4),
            ('sqlserver', 'server_roles', 'setupadmin', '设置管理员', 5),
            ('sqlserver', 'server_roles', 'bulkadmin', '批量操作管理员', 6),
            ('sqlserver', 'server_roles', 'diskadmin', '磁盘管理员', 7),
            ('sqlserver', 'server_roles', 'dbcreator', '数据库创建者', 8),
            ('sqlserver', 'server_roles', 'public', '公共角色', 9),

            # 数据库角色
            ('sqlserver', 'database_roles', 'db_owner', '数据库所有者', 1),
            ('sqlserver', 'database_roles', 'db_accessadmin', '访问管理员', 2),
            ('sqlserver', 'database_roles', 'db_securityadmin', '安全管理员', 3),
            ('sqlserver', 'database_roles', 'db_ddladmin', 'DDL管理员', 4),
            ('sqlserver', 'database_roles', 'db_backupoperator', '备份操作员', 5),
            ('sqlserver', 'database_roles', 'db_datareader', '数据读取者', 6),
            ('sqlserver', 'database_roles', 'db_datawriter', '数据写入者', 7),
            ('sqlserver', 'database_roles', 'db_denydatareader', '拒绝数据读取', 8),
            ('sqlserver', 'database_roles', 'db_denydatawriter', '拒绝数据写入', 9),

            # 服务器权限
            ('sqlserver', 'server_permissions', 'CONTROL SERVER', '控制服务器', 1),
            ('sqlserver', 'server_permissions', 'ALTER ANY LOGIN', '修改任意登录', 2),
            ('sqlserver', 'server_permissions', 'ALTER ANY SERVER ROLE', '修改任意服务器角色', 3),
            ('sqlserver', 'server_permissions', 'CREATE ANY DATABASE', '创建任意数据库', 4),
            ('sqlserver', 'server_permissions', 'ALTER ANY DATABASE', '修改任意数据库', 5),
            ('sqlserver', 'server_permissions', 'VIEW SERVER STATE', '查看服务器状态', 6),
            ('sqlserver', 'server_permissions', 'ALTER SERVER STATE', '修改服务器状态', 7),
            ('sqlserver', 'server_permissions', 'ALTER SETTINGS', '修改设置', 8),
            ('sqlserver', 'server_permissions', 'ALTER TRACE', '修改跟踪', 9),
            ('sqlserver', 'server_permissions', 'AUTHENTICATE SERVER', '服务器身份验证', 10),
            ('sqlserver', 'server_permissions', 'BACKUP DATABASE', '备份数据库', 11),
            ('sqlserver', 'server_permissions', 'BACKUP LOG', '备份日志', 12),
            ('sqlserver', 'server_permissions', 'CHECKPOINT', '检查点', 13),
            ('sqlserver', 'server_permissions', 'CONNECT SQL', '连接SQL', 14),
            ('sqlserver', 'server_permissions', 'SHUTDOWN', '关闭服务器', 15),
            ('sqlserver', 'server_permissions', 'IMPERSONATE ANY LOGIN', '模拟任意登录', 16),
            ('sqlserver', 'server_permissions', 'VIEW ANY DEFINITION', '查看任意定义', 17),
            ('sqlserver', 'server_permissions', 'VIEW ANY COLUMN ENCRYPTION KEY DEFINITION', '查看任意列加密密钥定义', 18),
            ('sqlserver', 'server_permissions', 'VIEW ANY COLUMN MASTER KEY DEFINITION', '查看任意列主密钥定义', 19),

            # 数据库权限
            ('sqlserver', 'database_privileges', 'SELECT', '查询数据', 1),
            ('sqlserver', 'database_privileges', 'INSERT', '插入数据', 2),
            ('sqlserver', 'database_privileges', 'UPDATE', '更新数据', 3),
            ('sqlserver', 'database_privileges', 'DELETE', '删除数据', 4),
            ('sqlserver', 'database_privileges', 'CREATE', '创建对象', 5),
            ('sqlserver', 'database_privileges', 'ALTER', '修改/删除对象（包含DROP功能）', 6),
            ('sqlserver', 'database_privileges', 'EXECUTE', '执行存储过程', 7),
            ('sqlserver', 'database_privileges', 'CONTROL', '完全控制权限', 8),
            ('sqlserver', 'database_privileges', 'REFERENCES', '引用权限', 9),
            ('sqlserver', 'database_privileges', 'VIEW DEFINITION', '查看定义', 10),
            ('sqlserver', 'database_privileges', 'TAKE OWNERSHIP', '获取所有权', 11),
            ('sqlserver', 'database_privileges', 'IMPERSONATE', '模拟权限', 12),
            ('sqlserver', 'database_privileges', 'CREATE SCHEMA', '创建架构', 13),
            ('sqlserver', 'database_privileges', 'ALTER ANY SCHEMA', '修改任意架构', 14),
            ('sqlserver', 'database_privileges', 'CREATE TABLE', '创建表', 15),
            ('sqlserver', 'database_privileges', 'CREATE VIEW', '创建视图', 16),
            ('sqlserver', 'database_privileges', 'CREATE PROCEDURE', '创建存储过程', 17),
            ('sqlserver', 'database_privileges', 'CREATE FUNCTION', '创建函数', 18),
            ('sqlserver', 'database_privileges', 'CREATE TRIGGER', '创建触发器', 19),
        ]

        # Oracle权限配置 - 基于SYS账户实际权限
        oracle_permissions = [
            # 系统权限（基于SYS账户实际权限，200个）
            ('oracle', 'system_privileges', 'ADMINISTER ANY SQL TUNING SET', '管理任意SQL调优集', 1),
            ('oracle', 'system_privileges', 'ADMINISTER DATABASE TRIGGER', '管理数据库触发器', 2),
            ('oracle', 'system_privileges', 'ADMINISTER RESOURCE MANAGER', '管理资源管理器', 3),
            ('oracle', 'system_privileges', 'ADMINISTER SQL MANAGEMENT OBJECT', '管理SQL管理对象', 4),
            ('oracle', 'system_privileges', 'ADMINISTER SQL TUNING SET', '管理SQL调优集', 5),
            ('oracle', 'system_privileges', 'ADVISOR', '顾问权限', 6),
            ('oracle', 'system_privileges', 'ALTER ANY ASSEMBLY', '修改任意程序集', 7),
            ('oracle', 'system_privileges', 'ALTER ANY CLUSTER', '修改任意集群', 8),
            ('oracle', 'system_privileges', 'ALTER ANY CUBE', '修改任意多维数据集', 9),
            ('oracle', 'system_privileges', 'ALTER ANY CUBE DIMENSION', '修改任意多维数据集维度', 10),
            ('oracle', 'system_privileges', 'ALTER ANY DIMENSION', '修改任意维度', 11),
            ('oracle', 'system_privileges', 'ALTER ANY EDITION', '修改任意版本', 12),
            ('oracle', 'system_privileges', 'ALTER ANY EVALUATION CONTEXT', '修改任意评估上下文', 13),
            ('oracle', 'system_privileges', 'ALTER ANY INDEX', '修改任意索引', 14),
            ('oracle', 'system_privileges', 'ALTER ANY INDEXTYPE', '修改任意索引类型', 15),
            ('oracle', 'system_privileges', 'ALTER ANY LIBRARY', '修改任意库', 16),
            ('oracle', 'system_privileges', 'ALTER ANY MATERIALIZED VIEW', '修改任意物化视图', 17),
            ('oracle', 'system_privileges', 'ALTER ANY MINING MODEL', '修改任意挖掘模型', 18),
            ('oracle', 'system_privileges', 'ALTER ANY OPERATOR', '修改任意操作符', 19),
            ('oracle', 'system_privileges', 'ALTER ANY OUTLINE', '修改任意大纲', 20),
            ('oracle', 'system_privileges', 'ALTER ANY PROCEDURE', '修改任意存储过程', 21),
            ('oracle', 'system_privileges', 'ALTER ANY ROLE', '修改任意角色', 22),
            ('oracle', 'system_privileges', 'ALTER ANY RULE', '修改任意规则', 23),
            ('oracle', 'system_privileges', 'ALTER ANY RULE SET', '修改任意规则集', 24),
            ('oracle', 'system_privileges', 'ALTER ANY SEQUENCE', '修改任意序列', 25),
            ('oracle', 'system_privileges', 'ALTER ANY SQL PROFILE', '修改任意SQL配置文件', 26),
            ('oracle', 'system_privileges', 'ALTER ANY TABLE', '修改任意表', 27),
            ('oracle', 'system_privileges', 'ALTER ANY TRIGGER', '修改任意触发器', 28),
            ('oracle', 'system_privileges', 'ALTER ANY TYPE', '修改任意类型', 29),
            ('oracle', 'system_privileges', 'ALTER DATABASE', '修改数据库', 30),
            ('oracle', 'system_privileges', 'ALTER PROFILE', '修改配置文件', 31),
            ('oracle', 'system_privileges', 'ALTER RESOURCE COST', '修改资源成本', 32),
            ('oracle', 'system_privileges', 'ALTER ROLLBACK SEGMENT', '修改回滚段', 33),
            ('oracle', 'system_privileges', 'ALTER SESSION', '修改会话', 34),
            ('oracle', 'system_privileges', 'ALTER SYSTEM', '修改系统', 35),
            ('oracle', 'system_privileges', 'ALTER TABLESPACE', '修改表空间', 36),
            ('oracle', 'system_privileges', 'ALTER USER', '修改用户', 37),
            ('oracle', 'system_privileges', 'ANALYZE ANY', '分析任意对象', 38),
            ('oracle', 'system_privileges', 'AUDIT ANY', '审计任意对象', 39),
            ('oracle', 'system_privileges', 'AUDIT SYSTEM', '审计系统', 40),
            ('oracle', 'system_privileges', 'BACKUP ANY TABLE', '备份任意表', 41),
            ('oracle', 'system_privileges', 'BECOME USER', '成为用户', 42),
            ('oracle', 'system_privileges', 'CHANGE NOTIFICATION', '变更通知', 43),
            ('oracle', 'system_privileges', 'COMMENT ANY MINING MODEL', '注释任意挖掘模型', 44),
            ('oracle', 'system_privileges', 'COMMENT ANY TABLE', '注释任意表', 45),
            ('oracle', 'system_privileges', 'CREATE ANY ASSEMBLY', '创建任意程序集', 46),
            ('oracle', 'system_privileges', 'CREATE ANY CLUSTER', '创建任意集群', 47),
            ('oracle', 'system_privileges', 'CREATE ANY CONTEXT', '创建任意上下文', 48),
            ('oracle', 'system_privileges', 'CREATE ANY CUBE', '创建任意多维数据集', 49),
            ('oracle', 'system_privileges', 'CREATE ANY CUBE BUILD PROCESS', '创建任意多维数据集构建过程', 50),
            ('oracle', 'system_privileges', 'CREATE ANY CUBE DIMENSION', '创建任意多维数据集维度', 51),
            ('oracle', 'system_privileges', 'CREATE ANY DIMENSION', '创建任意维度', 52),
            ('oracle', 'system_privileges', 'CREATE ANY DIRECTORY', '创建任意目录', 53),
            ('oracle', 'system_privileges', 'CREATE ANY EDITION', '创建任意版本', 54),
            ('oracle', 'system_privileges', 'CREATE ANY EVALUATION CONTEXT', '创建任意评估上下文', 55),
            ('oracle', 'system_privileges', 'CREATE ANY INDEX', '创建任意索引', 56),
            ('oracle', 'system_privileges', 'CREATE ANY INDEXTYPE', '创建任意索引类型', 57),
            ('oracle', 'system_privileges', 'CREATE ANY JOB', '创建任意作业', 58),
            ('oracle', 'system_privileges', 'CREATE ANY LIBRARY', '创建任意库', 59),
            ('oracle', 'system_privileges', 'CREATE ANY MATERIALIZED VIEW', '创建任意物化视图', 60),
            ('oracle', 'system_privileges', 'CREATE ANY MEASURE FOLDER', '创建任意度量文件夹', 61),
            ('oracle', 'system_privileges', 'CREATE ANY MINING MODEL', '创建任意挖掘模型', 62),
            ('oracle', 'system_privileges', 'CREATE ANY OPERATOR', '创建任意操作符', 63),
            ('oracle', 'system_privileges', 'CREATE ANY OUTLINE', '创建任意大纲', 64),
            ('oracle', 'system_privileges', 'CREATE ANY PROCEDURE', '创建任意存储过程', 65),
            ('oracle', 'system_privileges', 'CREATE ANY RULE', '创建任意规则', 66),
            ('oracle', 'system_privileges', 'CREATE ANY RULE SET', '创建任意规则集', 67),
            ('oracle', 'system_privileges', 'CREATE ANY SEQUENCE', '创建任意序列', 68),
            ('oracle', 'system_privileges', 'CREATE ANY SQL PROFILE', '创建任意SQL配置文件', 69),
            ('oracle', 'system_privileges', 'CREATE ANY SYNONYM', '创建任意同义词', 70),
            ('oracle', 'system_privileges', 'CREATE ANY TABLE', '创建任意表', 71),
            ('oracle', 'system_privileges', 'CREATE ANY TRIGGER', '创建任意触发器', 72),
            ('oracle', 'system_privileges', 'CREATE ANY TYPE', '创建任意类型', 73),
            ('oracle', 'system_privileges', 'CREATE ANY VIEW', '创建任意视图', 74),
            ('oracle', 'system_privileges', 'CREATE ASSEMBLY', '创建程序集', 75),
            ('oracle', 'system_privileges', 'CREATE CLUSTER', '创建集群', 76),
            ('oracle', 'system_privileges', 'CREATE CUBE', '创建多维数据集', 77),
            ('oracle', 'system_privileges', 'CREATE CUBE BUILD PROCESS', '创建多维数据集构建过程', 78),
            ('oracle', 'system_privileges', 'CREATE CUBE DIMENSION', '创建多维数据集维度', 79),
            ('oracle', 'system_privileges', 'CREATE DATABASE LINK', '创建数据库链接', 80),
            ('oracle', 'system_privileges', 'CREATE DIMENSION', '创建维度', 81),
            ('oracle', 'system_privileges', 'CREATE EVALUATION CONTEXT', '创建评估上下文', 82),
            ('oracle', 'system_privileges', 'CREATE EXTERNAL JOB', '创建外部作业', 83),
            ('oracle', 'system_privileges', 'CREATE INDEXTYPE', '创建索引类型', 84),
            ('oracle', 'system_privileges', 'CREATE JOB', '创建作业', 85),
            ('oracle', 'system_privileges', 'CREATE LIBRARY', '创建库', 86),
            ('oracle', 'system_privileges', 'CREATE MATERIALIZED VIEW', '创建物化视图', 87),
            ('oracle', 'system_privileges', 'CREATE MEASURE FOLDER', '创建度量文件夹', 88),
            ('oracle', 'system_privileges', 'CREATE MINING MODEL', '创建挖掘模型', 89),
            ('oracle', 'system_privileges', 'CREATE OPERATOR', '创建操作符', 90),
            ('oracle', 'system_privileges', 'CREATE PROCEDURE', '创建存储过程', 91),
            ('oracle', 'system_privileges', 'CREATE PROFILE', '创建配置文件', 92),
            ('oracle', 'system_privileges', 'CREATE PUBLIC DATABASE LINK', '创建公共数据库链接', 93),
            ('oracle', 'system_privileges', 'CREATE ROLE', '创建角色', 94),
            ('oracle', 'system_privileges', 'CREATE ROLLBACK SEGMENT', '创建回滚段', 95),
            ('oracle', 'system_privileges', 'CREATE RULE', '创建规则', 96),
            ('oracle', 'system_privileges', 'CREATE RULE SET', '创建规则集', 97),
            ('oracle', 'system_privileges', 'CREATE SEQUENCE', '创建序列', 98),
            ('oracle', 'system_privileges', 'CREATE SESSION', '创建会话', 99),
            ('oracle', 'system_privileges', 'CREATE SYNONYM', '创建同义词', 100),
            ('oracle', 'system_privileges', 'CREATE TABLE', '创建表', 101),
            ('oracle', 'system_privileges', 'CREATE TABLESPACE', '创建表空间', 102),
            ('oracle', 'system_privileges', 'CREATE TRIGGER', '创建触发器', 103),
            ('oracle', 'system_privileges', 'CREATE TYPE', '创建类型', 104),
            ('oracle', 'system_privileges', 'CREATE USER', '创建用户', 105),
            ('oracle', 'system_privileges', 'CREATE VIEW', '创建视图', 106),
            ('oracle', 'system_privileges', 'DEBUG ANY PROCEDURE', '调试任意存储过程', 107),
            ('oracle', 'system_privileges', 'DEBUG CONNECT SESSION', '调试连接会话', 108),
            ('oracle', 'system_privileges', 'DELETE ANY CUBE DIMENSION', '删除任意多维数据集维度', 109),
            ('oracle', 'system_privileges', 'DELETE ANY MEASURE FOLDER', '删除任意度量文件夹', 110),
            ('oracle', 'system_privileges', 'DELETE ANY TABLE', '删除任意表', 111),
            ('oracle', 'system_privileges', 'DEQUEUE ANY QUEUE', '出队任意队列', 112),
            ('oracle', 'system_privileges', 'DROP ANY ASSEMBLY', '删除任意程序集', 113),
            ('oracle', 'system_privileges', 'DROP ANY CLUSTER', '删除任意集群', 114),
            ('oracle', 'system_privileges', 'DROP ANY CONTEXT', '删除任意上下文', 115),
            ('oracle', 'system_privileges', 'DROP ANY CUBE', '删除任意多维数据集', 116),
            ('oracle', 'system_privileges', 'DROP ANY CUBE BUILD PROCESS', '删除任意多维数据集构建过程', 117),
            ('oracle', 'system_privileges', 'DROP ANY CUBE DIMENSION', '删除任意多维数据集维度', 118),
            ('oracle', 'system_privileges', 'DROP ANY DIMENSION', '删除任意维度', 119),
            ('oracle', 'system_privileges', 'DROP ANY DIRECTORY', '删除任意目录', 120),
            ('oracle', 'system_privileges', 'DROP ANY EDITION', '删除任意版本', 121),
            ('oracle', 'system_privileges', 'DROP ANY EVALUATION CONTEXT', '删除任意评估上下文', 122),
            ('oracle', 'system_privileges', 'DROP ANY INDEX', '删除任意索引', 123),
            ('oracle', 'system_privileges', 'DROP ANY INDEXTYPE', '删除任意索引类型', 124),
            ('oracle', 'system_privileges', 'DROP ANY LIBRARY', '删除任意库', 125),
            ('oracle', 'system_privileges', 'DROP ANY MATERIALIZED VIEW', '删除任意物化视图', 126),
            ('oracle', 'system_privileges', 'DROP ANY MEASURE FOLDER', '删除任意度量文件夹', 127),
            ('oracle', 'system_privileges', 'DROP ANY MINING MODEL', '删除任意挖掘模型', 128),
            ('oracle', 'system_privileges', 'DROP ANY OPERATOR', '删除任意操作符', 129),
            ('oracle', 'system_privileges', 'DROP ANY OUTLINE', '删除任意大纲', 130),
            ('oracle', 'system_privileges', 'DROP ANY PROCEDURE', '删除任意存储过程', 131),
            ('oracle', 'system_privileges', 'DROP ANY ROLE', '删除任意角色', 132),
            ('oracle', 'system_privileges', 'DROP ANY RULE', '删除任意规则', 133),
            ('oracle', 'system_privileges', 'DROP ANY RULE SET', '删除任意规则集', 134),
            ('oracle', 'system_privileges', 'DROP ANY SEQUENCE', '删除任意序列', 135),
            ('oracle', 'system_privileges', 'DROP ANY SQL PROFILE', '删除任意SQL配置文件', 136),
            ('oracle', 'system_privileges', 'DROP ANY SYNONYM', '删除任意同义词', 137),
            ('oracle', 'system_privileges', 'DROP ANY TABLE', '删除任意表', 138),
            ('oracle', 'system_privileges', 'DROP ANY TRIGGER', '删除任意触发器', 139),
            ('oracle', 'system_privileges', 'DROP ANY TYPE', '删除任意类型', 140),
            ('oracle', 'system_privileges', 'DROP ANY VIEW', '删除任意视图', 141),
            ('oracle', 'system_privileges', 'DROP PROFILE', '删除配置文件', 142),
            ('oracle', 'system_privileges', 'DROP PUBLIC DATABASE LINK', '删除公共数据库链接', 143),
            ('oracle', 'system_privileges', 'DROP PUBLIC SYNONYM', '删除公共同义词', 144),
            ('oracle', 'system_privileges', 'DROP ROLLBACK SEGMENT', '删除回滚段', 145),
            ('oracle', 'system_privileges', 'DROP TABLESPACE', '删除表空间', 146),
            ('oracle', 'system_privileges', 'DROP USER', '删除用户', 147),
            ('oracle', 'system_privileges', 'ENQUEUE ANY QUEUE', '入队任意队列', 148),
            ('oracle', 'system_privileges', 'EXECUTE ANY ASSEMBLY', '执行任意程序集', 149),
            ('oracle', 'system_privileges', 'EXECUTE ANY CLASS', '执行任意类', 150),
            ('oracle', 'system_privileges', 'EXECUTE ANY EVALUATION CONTEXT', '执行任意评估上下文', 151),
            ('oracle', 'system_privileges', 'EXECUTE ANY INDEXTYPE', '执行任意索引类型', 152),
            ('oracle', 'system_privileges', 'EXECUTE ANY LIBRARY', '执行任意库', 153),
            ('oracle', 'system_privileges', 'EXECUTE ANY OPERATOR', '执行任意操作符', 154),
            ('oracle', 'system_privileges', 'EXECUTE ANY PROCEDURE', '执行任意存储过程', 155),
            ('oracle', 'system_privileges', 'EXECUTE ANY PROGRAM', '执行任意程序', 156),
            ('oracle', 'system_privileges', 'EXECUTE ANY RULE', '执行任意规则', 157),
            ('oracle', 'system_privileges', 'EXECUTE ANY RULE SET', '执行任意规则集', 158),
            ('oracle', 'system_privileges', 'EXECUTE ANY TYPE', '执行任意类型', 159),
            ('oracle', 'system_privileges', 'EXECUTE ASSEMBLY', '执行程序集', 160),
            ('oracle', 'system_privileges', 'EXPORT FULL DATABASE', '导出完整数据库', 161),
            ('oracle', 'system_privileges', 'FLASHBACK ANY TABLE', '闪回任意表', 162),
            ('oracle', 'system_privileges', 'FLASHBACK ARCHIVE ADMINISTER', '闪回归档管理', 163),
            ('oracle', 'system_privileges', 'FORCE ANY TRANSACTION', '强制任意事务', 164),
            ('oracle', 'system_privileges', 'FORCE TRANSACTION', '强制事务', 165),
            ('oracle', 'system_privileges', 'GLOBAL QUERY REWRITE', '全局查询重写', 166),
            ('oracle', 'system_privileges', 'GRANT ANY OBJECT PRIVILEGE', '授予任意对象权限', 167),
            ('oracle', 'system_privileges', 'GRANT ANY PRIVILEGE', '授予任意权限', 168),
            ('oracle', 'system_privileges', 'GRANT ANY ROLE', '授予任意角色', 169),
            ('oracle', 'system_privileges', 'IMPORT FULL DATABASE', '导入完整数据库', 170),
            ('oracle', 'system_privileges', 'INSERT ANY CUBE DIMENSION', '插入任意多维数据集维度', 171),
            ('oracle', 'system_privileges', 'INSERT ANY MEASURE FOLDER', '插入任意度量文件夹', 172),
            ('oracle', 'system_privileges', 'INSERT ANY TABLE', '插入任意表', 173),
            ('oracle', 'system_privileges', 'LOCK ANY TABLE', '锁定任意表', 174),
            ('oracle', 'system_privileges', 'MANAGE ANY FILE GROUP', '管理任意文件组', 175),
            ('oracle', 'system_privileges', 'MANAGE ANY QUEUE', '管理任意队列', 176),
            ('oracle', 'system_privileges', 'MANAGE FILE GROUP', '管理文件组', 177),
            ('oracle', 'system_privileges', 'MANAGE SCHEDULER', '管理调度器', 178),
            ('oracle', 'system_privileges', 'MANAGE TABLESPACE', '管理表空间', 179),
            ('oracle', 'system_privileges', 'MERGE ANY VIEW', '合并任意视图', 180),
            ('oracle', 'system_privileges', 'ON COMMIT REFRESH', '提交时刷新', 181),
            ('oracle', 'system_privileges', 'QUERY REWRITE', '查询重写', 182),
            ('oracle', 'system_privileges', 'READ ANY FILE GROUP', '读取任意文件组', 183),
            ('oracle', 'system_privileges', 'RESTRICTED SESSION', '受限会话', 184),
            ('oracle', 'system_privileges', 'RESUMABLE', '可恢复', 185),
            ('oracle', 'system_privileges', 'SELECT ANY CUBE', '查询任意多维数据集', 186),
            ('oracle', 'system_privileges', 'SELECT ANY CUBE DIMENSION', '查询任意多维数据集维度', 187),
            ('oracle', 'system_privileges', 'SELECT ANY MINING MODEL', '查询任意挖掘模型', 188),
            ('oracle', 'system_privileges', 'SELECT ANY SEQUENCE', '查询任意序列', 189),
            ('oracle', 'system_privileges', 'SELECT ANY TABLE', '查询任意表', 190),
            ('oracle', 'system_privileges', 'SELECT ANY TRANSACTION', '查询任意事务', 191),
            ('oracle', 'system_privileges', 'UNDER ANY TABLE', '任意表下', 192),
            ('oracle', 'system_privileges', 'UNDER ANY TYPE', '任意类型下', 193),
            ('oracle', 'system_privileges', 'UNDER ANY VIEW', '任意视图下', 194),
            ('oracle', 'system_privileges', 'UNLIMITED TABLESPACE', '无限制表空间', 195),
            ('oracle', 'system_privileges', 'UPDATE ANY CUBE', '更新任意多维数据集', 196),
            ('oracle', 'system_privileges', 'UPDATE ANY CUBE BUILD PROCESS', '更新任意多维数据集构建过程', 197),
            ('oracle', 'system_privileges', 'UPDATE ANY CUBE DIMENSION', '更新任意多维数据集维度', 198),
            ('oracle', 'system_privileges', 'UPDATE ANY TABLE', '更新任意表', 199),
            ('oracle', 'system_privileges', 'INSERT ANY TABLE', '插入任意表', 200),

            # Oracle角色（67个）
            ('oracle', 'roles', 'ADM_PARALLEL_EXECUTE_TASK', '并行执行任务管理角色', 1),
            ('oracle', 'roles', 'APEX_ADMINISTRATOR_ROLE', 'APEX管理员角色', 2),
            ('oracle', 'roles', 'AQ_ADMINISTRATOR_ROLE', '高级队列管理员角色', 3),
            ('oracle', 'roles', 'AQ_USER_ROLE', '高级队列用户角色', 4),
            ('oracle', 'roles', 'AUDIT_ADMIN', '审计管理员角色', 5),
            ('oracle', 'roles', 'AUDIT_VIEWER', '审计查看者角色', 6),
            ('oracle', 'roles', 'AUTHENTICATEDUSER', '认证用户角色', 7),
            ('oracle', 'roles', 'CDB_DBA', 'CDB数据库管理员角色', 8),
            ('oracle', 'roles', 'CONNECT', '连接角色', 9),
            ('oracle', 'roles', 'CTXAPP', '文本应用角色', 10),
            ('oracle', 'roles', 'DBA', '数据库管理员角色', 11),
            ('oracle', 'roles', 'DBFS_ROLE', '数据库文件系统角色', 12),
            ('oracle', 'roles', 'DV_ACCTMGR', '数据库保险库账户管理器角色', 13),
            ('oracle', 'roles', 'DV_ADMIN', '数据库保险库管理员角色', 14),
            ('oracle', 'roles', 'DV_AUDIT_CLEANUP', '数据库保险库审计清理角色', 15),
            ('oracle', 'roles', 'DV_DATAPUMP_EXP_FULL_DATABASE', '数据库保险库数据泵导出完整数据库角色', 16),
            ('oracle', 'roles', 'DV_DATAPUMP_IMP_FULL_DATABASE', '数据库保险库数据泵导入完整数据库角色', 17),
            ('oracle', 'roles', 'DV_GATHER_SYSTEM_STATISTICS', '数据库保险库收集系统统计信息角色', 18),
            ('oracle', 'roles', 'DV_MONITOR', '数据库保险库监控角色', 19),
            ('oracle', 'roles', 'DV_OWNER', '数据库保险库所有者角色', 20),
            ('oracle', 'roles', 'DV_PATCH_ADMIN', '数据库保险库补丁管理员角色', 21),
            ('oracle', 'roles', 'DV_POLICY_OWNER', '数据库保险库策略所有者角色', 22),
            ('oracle', 'roles', 'DV_PUBLIC', '数据库保险库公共角色', 23),
            ('oracle', 'roles', 'DV_REALM_OWNER', '数据库保险库领域所有者角色', 24),
            ('oracle', 'roles', 'DV_REALM_RESOURCE', '数据库保险库领域资源角色', 25),
            ('oracle', 'roles', 'DV_SECANALYST', '数据库保险库安全分析师角色', 26),
            ('oracle', 'roles', 'DV_SELECT_CATALOG_ROLE', '数据库保险库选择目录角色', 27),
            ('oracle', 'roles', 'DV_SITE_ADMIN', '数据库保险库站点管理员角色', 28),
            ('oracle', 'roles', 'DV_STREAMS_ADMIN', '数据库保险库流管理员角色', 29),
            ('oracle', 'roles', 'DV_TABLESPACE_QUOTA', '数据库保险库表空间配额角色', 30),
            ('oracle', 'roles', 'DV_XSTREAM_ADMIN', '数据库保险库XStream管理员角色', 31),
            ('oracle', 'roles', 'EM_EXPRESS_ALL', '企业管理器Express所有角色', 32),
            ('oracle', 'roles', 'EM_EXPRESS_BASIC', '企业管理器Express基础角色', 33),
            ('oracle', 'roles', 'EXECUTE_CATALOG_ROLE', '执行目录角色', 34),
            ('oracle', 'roles', 'EXP_FULL_DATABASE', '导出完整数据库角色', 35),
            ('oracle', 'roles', 'GATHER_SYSTEM_STATISTICS', '收集系统统计信息角色', 36),
            ('oracle', 'roles', 'GLOBAL_AQ_USER_ROLE', '全局高级队列用户角色', 37),
            ('oracle', 'roles', 'HS_ADMIN_EXECUTE_ROLE', '异构服务管理员执行角色', 38),
            ('oracle', 'roles', 'HS_ADMIN_ROLE', '异构服务管理员角色', 39),
            ('oracle', 'roles', 'HS_ADMIN_SELECT_ROLE', '异构服务管理员选择角色', 40),
            ('oracle', 'roles', 'IMP_FULL_DATABASE', '导入完整数据库角色', 41),
            ('oracle', 'roles', 'JAVADEBUGPRIV', 'Java调试权限角色', 42),
            ('oracle', 'roles', 'JAVAUSERPRIV', 'Java用户权限角色', 43),
            ('oracle', 'roles', 'JAVA_ADMIN', 'Java管理员角色', 44),
            ('oracle', 'roles', 'JAVA_DEPLOY', 'Java部署角色', 45),
            ('oracle', 'roles', 'JMXSERVER', 'JMX服务器角色', 46),
            ('oracle', 'roles', 'LOGSTDBY_ADMINISTRATOR', '逻辑备用数据库管理员角色', 47),
            ('oracle', 'roles', 'OEM_ADVISOR', 'OEM顾问角色', 48),
            ('oracle', 'roles', 'OEM_MONITOR', 'OEM监控角色', 49),
            ('oracle', 'roles', 'OLAP_DBA', 'OLAP数据库管理员角色', 50),
            ('oracle', 'roles', 'OLAP_USER', 'OLAP用户角色', 51),
            ('oracle', 'roles', 'OLAP_XS_ADMIN', 'OLAP XS管理员角色', 52),
            ('oracle', 'roles', 'OLAP_XS_APP_ADMIN', 'OLAP XS应用管理员角色', 53),
            ('oracle', 'roles', 'OLAP_XS_CACHE_ADMIN', 'OLAP XS缓存管理员角色', 54),
            ('oracle', 'roles', 'OLAP_XS_SESSION_ADMIN', 'OLAP XS会话管理员角色', 55),
            ('oracle', 'roles', 'ORDADMIN', 'Oracle多媒体管理员角色', 56),
            ('oracle', 'roles', 'ORDPLUGINS', 'Oracle多媒体插件角色', 57),
            ('oracle', 'roles', 'ORDSYS', 'Oracle多媒体系统角色', 58),
            ('oracle', 'roles', 'PDB_DBA', 'PDB数据库管理员角色', 59),
            ('oracle', 'roles', 'PLUSTRACE', 'PL/SQL跟踪角色', 60),
            ('oracle', 'roles', 'RECOVERY_CATALOG_OWNER', '恢复目录所有者角色', 61),
            ('oracle', 'roles', 'RESOURCE', '资源角色', 62),
            ('oracle', 'roles', 'SCHEDULER_ADMIN', '调度器管理员角色', 63),
            ('oracle', 'roles', 'SELECT_CATALOG_ROLE', '选择目录角色', 64),
            ('oracle', 'roles', 'WM_ADMIN_ROLE', '工作区管理器管理员角色', 65),
            ('oracle', 'roles', 'XDBADMIN', 'XML数据库管理员角色', 66),
            ('oracle', 'roles', 'XDB_SET_INVOKER', 'XML数据库设置调用者角色', 67),

            # Oracle表空间权限（21个）
            ('oracle', 'tablespace_privileges', 'ALTER ANY TABLESPACE', '修改任意表空间权限', 1),
            ('oracle', 'tablespace_privileges', 'ALTER TABLESPACE', '修改表空间权限', 2),
            ('oracle', 'tablespace_privileges', 'CREATE ANY TABLESPACE', '创建任意表空间权限', 3),
            ('oracle', 'tablespace_privileges', 'CREATE TABLESPACE', '创建表空间权限', 4),
            ('oracle', 'tablespace_privileges', 'DEBUG ANY TABLESPACE', '调试任意表空间权限', 5),
            ('oracle', 'tablespace_privileges', 'DEBUG TABLESPACE', '调试表空间权限', 6),
            ('oracle', 'tablespace_privileges', 'DROP ANY TABLESPACE', '删除任意表空间权限', 7),
            ('oracle', 'tablespace_privileges', 'DROP TABLESPACE', '删除表空间权限', 8),
            ('oracle', 'tablespace_privileges', 'MANAGE ANY TABLESPACE', '管理任意表空间权限', 9),
            ('oracle', 'tablespace_privileges', 'MANAGE TABLESPACE', '管理表空间权限', 10),
            ('oracle', 'tablespace_privileges', 'ON COMMIT REFRESH', '提交时刷新权限', 11),
            ('oracle', 'tablespace_privileges', 'QUERY REWRITE', '查询重写权限', 12),
            ('oracle', 'tablespace_privileges', 'READ ANY TABLESPACE', '读取任意表空间权限', 13),
            ('oracle', 'tablespace_privileges', 'READ TABLESPACE', '读取表空间权限', 14),
            ('oracle', 'tablespace_privileges', 'SELECT ANY TABLESPACE', '查询任意表空间权限', 15),
            ('oracle', 'tablespace_privileges', 'SELECT TABLESPACE', '查询表空间权限', 16),
            ('oracle', 'tablespace_privileges', 'UNLIMITED TABLESPACE', '无限制表空间权限', 17),
            ('oracle', 'tablespace_privileges', 'UPDATE ANY TABLESPACE', '更新任意表空间权限', 18),
            ('oracle', 'tablespace_privileges', 'UPDATE TABLESPACE', '更新表空间权限', 19),
            ('oracle', 'tablespace_privileges', 'WRITE ANY TABLESPACE', '写入任意表空间权限', 20),
            ('oracle', 'tablespace_privileges', 'WRITE TABLESPACE', '写入表空间权限', 21),

            # Oracle表空间配额（25个）
            ('oracle', 'tablespace_quotas', 'DEFAULT', '默认配额', 1),
            ('oracle', 'tablespace_quotas', 'NO QUOTA', '无配额', 2),
            ('oracle', 'tablespace_quotas', 'QUOTA', '配额', 3),
            ('oracle', 'tablespace_quotas', 'QUOTA 100E', '100E配额', 4),
            ('oracle', 'tablespace_quotas', 'QUOTA 100G', '100G配额', 5),
            ('oracle', 'tablespace_quotas', 'QUOTA 100K', '100K配额', 6),
            ('oracle', 'tablespace_quotas', 'QUOTA 100M', '100M配额', 7),
            ('oracle', 'tablespace_quotas', 'QUOTA 100P', '100P配额', 8),
            ('oracle', 'tablespace_quotas', 'QUOTA 100T', '100T配额', 9),
            ('oracle', 'tablespace_quotas', 'QUOTA 10E', '10E配额', 10),
            ('oracle', 'tablespace_quotas', 'QUOTA 10G', '10G配额', 11),
            ('oracle', 'tablespace_quotas', 'QUOTA 10K', '10K配额', 12),
            ('oracle', 'tablespace_quotas', 'QUOTA 10M', '10M配额', 13),
            ('oracle', 'tablespace_quotas', 'QUOTA 10P', '10P配额', 14),
            ('oracle', 'tablespace_quotas', 'QUOTA 10T', '10T配额', 15),
            ('oracle', 'tablespace_quotas', 'QUOTA 1E', '1E配额', 16),
            ('oracle', 'tablespace_quotas', 'QUOTA 1G', '1G配额', 17),
            ('oracle', 'tablespace_quotas', 'QUOTA 1K', '1K配额', 18),
            ('oracle', 'tablespace_quotas', 'QUOTA 1M', '1M配额', 19),
            ('oracle', 'tablespace_quotas', 'QUOTA 1P', '1P配额', 20),
            ('oracle', 'tablespace_quotas', 'QUOTA 1T', '1T配额', 21),
            ('oracle', 'tablespace_quotas', 'QUOTA UNLIMITED', '无限制配额', 22),
            ('oracle', 'tablespace_quotas', 'QUOTA 0', '0配额', 23),
            ('oracle', 'tablespace_quotas', 'QUOTA 5G', '5G配额', 24),
            ('oracle', 'tablespace_quotas', 'QUOTA 50G', '50G配额', 25),
        ]

        # 添加所有权限配置
        all_permissions = mysql_permissions + postgresql_permissions + sqlserver_permissions + oracle_permissions

        print(f"开始添加 {len(all_permissions)} 个权限配置...")

        # 检查重复权限
        seen_permissions = set()
        unique_permissions = []

        for db_type, category, permission_name, description, sort_order in all_permissions:
            key = (db_type, category, permission_name)
            if key not in seen_permissions:
                seen_permissions.add(key)
                unique_permissions.append((db_type, category, permission_name, description, sort_order))
            else:
                print(f"跳过重复权限: {db_type}.{category}.{permission_name}")

        print(f"去重后权限配置: {len(unique_permissions)}个")

        for db_type, category, permission_name, description, sort_order in unique_permissions:
            permission_config = PermissionConfig(
                db_type=db_type,
                category=category,
                permission_name=permission_name,
                description=description,
                is_active=True,
                sort_order=sort_order,
                created_at=datetime.utcnow(),
                updated_at=datetime.utcnow()
            )
            db.session.add(permission_config)

        # 提交更改
        db.session.commit()

        print("权限配置初始化完成！")

        # 验证结果
        total_perms = PermissionConfig.query.count()
        print(f"总计权限配置: {total_perms}个")

        for db_type in ['mysql', 'postgresql', 'sqlserver', 'oracle']:
            count = PermissionConfig.query.filter_by(db_type=db_type).count()
            print(f"  {db_type.upper()}: {count}个")

if __name__ == '__main__':
    init_permission_config()
